/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectpemvis_modul2;

import javax.swing.JOptionPane;

/**
 *
 * @author firak
 */
public class gajikaryawan extends javax.swing.JFrame {

    private int tarifPerJam;
    private int jamKerja;
    
    public gajikaryawan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfjamkerja = new javax.swing.JTextField();
        tftarif = new javax.swing.JTextField();
        tfgajibruto = new javax.swing.JTextField();
        tfgajibersih = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bgajibruto = new javax.swing.JButton();
        bgajibersih = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Jumlah jam kerja per Minggu");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(6, 70, 180, 20);

        jLabel2.setText("Tarif per jam");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(6, 110, 120, 20);

        jLabel3.setText("Gaji Bruto");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(6, 197, 100, 20);

        jLabel4.setText("Gaji Bersih");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(6, 278, 100, 20);

        tfjamkerja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfjamkerjaActionPerformed(evt);
            }
        });
        getContentPane().add(tfjamkerja);
        tfjamkerja.setBounds(227, 67, 144, 30);
        getContentPane().add(tftarif);
        tftarif.setBounds(227, 107, 144, 30);

        tfgajibruto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfgajibrutoActionPerformed(evt);
            }
        });
        getContentPane().add(tfgajibruto);
        tfgajibruto.setBounds(227, 194, 144, 30);

        tfgajibersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfgajibersihActionPerformed(evt);
            }
        });
        getContentPane().add(tfgajibersih);
        tfgajibersih.setBounds(227, 275, 144, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("RIncian Gaji Karyawan ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 10, 365, 34);

        bgajibruto.setText("Hitung Gaji Bruto");
        bgajibruto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgajibrutoActionPerformed(evt);
            }
        });
        getContentPane().add(bgajibruto);
        bgajibruto.setBounds(227, 153, 144, 30);

        bgajibersih.setText("Hitung Gaji Bersih");
        bgajibersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgajibersihActionPerformed(evt);
            }
        });
        getContentPane().add(bgajibersih);
        bgajibersih.setBounds(227, 234, 144, 30);

        jLabel6.setText("Rincian gaji bruto yang diperoleh");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(6, 156, 190, 20);

        jLabel7.setText("Rincian gaji bersih yang diperoleh");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(6, 237, 190, 20);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\firak\\Downloads\\Download premium image of Paper texture background, simple design by mook about white paper texture, plain cream background, cream paper texture, paper texture, and paper texture background 6418185.jpeg")); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 400, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfjamkerjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfjamkerjaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfjamkerjaActionPerformed

    private void tfgajibrutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfgajibrutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfgajibrutoActionPerformed

    private void tfgajibersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfgajibersihActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfgajibersihActionPerformed

    private void bgajibrutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgajibrutoActionPerformed
        // TODO add your handling code here:
        try { //kondisi 
            // Dapatkan tarif per jam dan jumlah jam kerja dari input field
            tarifPerJam = Integer.parseInt(tftarif.getText());
            jamKerja = Integer.parseInt(tfjamkerja.getText());

            // Hitung gaji bruto berdasarkan jumlah jam kerja
            int gajiAwal;
            if (jamKerja <= 40) {
                gajiAwal = jamKerja * tarifPerJam;
            } else {
                gajiAwal = 40 * tarifPerJam + (jamKerja - 40) * (tarifPerJam * 15 / 10); // 1.5 kali lipat
            }

            // Tampilkan hasil gaji bruto di dalam TextField tfBruto
            tfgajibruto.setText("Rp. " + gajiAwal);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Masukkan jumlah jam kerja dan tarif per jam yang valid.");
        }
        
    }//GEN-LAST:event_bgajibrutoActionPerformed

    private void bgajibersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgajibersihActionPerformed
        // TODO add your handling code here:
        try {
            // Periksa apakah tarifPerJam dan jamKerja sudah diisi
            if (tarifPerJam == 0 || jamKerja == 0) {
                JOptionPane.showMessageDialog(this, "Isi jumlah jam kerja dan tarif per jam terlebih dahulu.");
                return;
            }

            // Konstanta pajak
            double pajak = 0.1;

            // Hitung gaji bruto berdasarkan jumlah jam kerja
            int gajiAwal;
            if (jamKerja <= 40) {
                gajiAwal = jamKerja * tarifPerJam;
            } else {
                gajiAwal = 40 * tarifPerJam + (jamKerja - 40) * (tarifPerJam * 15 / 10); // 1.5 kali lipat
            }

            // Hitung gaji bersih setelah potongan pajak
            double gajiBersih = gajiAwal - (gajiAwal * pajak);

            // Tampilkan hasil gaji bersih di dalam TextField tfBersih
            tfgajibersih.setText("Rp. " + gajiBersih);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Masukkan jumlah jam kerja dan tarif per jam yang valid.");
        }
    }//GEN-LAST:event_bgajibersihActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gajikaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gajikaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gajikaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gajikaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gajikaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bgajibersih;
    private javax.swing.JButton bgajibruto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField tfgajibersih;
    private javax.swing.JTextField tfgajibruto;
    private javax.swing.JTextField tfjamkerja;
    private javax.swing.JTextField tftarif;
    // End of variables declaration//GEN-END:variables
}
